[package]
name = "carajillo"
version = "0.1.0"
authors = ["Andrew Zah <zah@andrewzah.com>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
argh = "0.1"
quick-xml = { version = "0.22", features = [ "serialize" ] }
serde = { version = "1.0", features = [ "derive" ] }
ureq = "2.1"
